// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9T_DOgBSw8qPVnQamPiRPmfD8Smi9RNA',
    appId: '1:585485006925:web:4deba9896acc344a6f8404',
    messagingSenderId: '585485006925',
    projectId: 'umrah-guide-53296',
    authDomain: 'umrah-guide-53296.firebaseapp.com',
    storageBucket: 'umrah-guide-53296.firebasestorage.app',
    measurementId: 'G-STWLNV60HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmTLXEkTHvY03MMxypmO9o69KUUsJuF6M',
    appId: '1:585485006925:android:5bcb3a8cdc2e3a926f8404',
    messagingSenderId: '585485006925',
    projectId: 'umrah-guide-53296',
    storageBucket: 'umrah-guide-53296.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRcur2F41kVDsgLFvpy2QlBurQG7zoZYQ',
    appId: '1:585485006925:ios:0dfa5568a49553b96f8404',
    messagingSenderId: '585485006925',
    projectId: 'umrah-guide-53296',
    storageBucket: 'umrah-guide-53296.firebasestorage.app',
    iosBundleId: 'com.example.umrahGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRcur2F41kVDsgLFvpy2QlBurQG7zoZYQ',
    appId: '1:585485006925:ios:0dfa5568a49553b96f8404',
    messagingSenderId: '585485006925',
    projectId: 'umrah-guide-53296',
    storageBucket: 'umrah-guide-53296.firebasestorage.app',
    iosBundleId: 'com.example.umrahGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9T_DOgBSw8qPVnQamPiRPmfD8Smi9RNA',
    appId: '1:585485006925:web:d05c9fd3361e04b56f8404',
    messagingSenderId: '585485006925',
    projectId: 'umrah-guide-53296',
    authDomain: 'umrah-guide-53296.firebaseapp.com',
    storageBucket: 'umrah-guide-53296.firebasestorage.app',
    measurementId: 'G-WYQM8WZ93L',
  );
}
